/* Support-to-Tech Classroom — slide content for all 42 sessions.
   One object per session. Used by BOTH the HTML deck and the PPTX generator.
   hook = story lines revealed one by one · q = discussion question
   ex = explainer slides (max 4 short points) · cmp = comparison slide
   wow = [big stat, caption] · handoff = lab line · demo = interactive widget id (HTML deck only)
   notes = what YOU say (presenter notes, never shown to the room) */
const SESSIONS=[
{n:1,title:"How computers think",
hook:["1947. Harvard's Mark II computer fails.","The technicians open it up and find… a moth.","They tape it in the logbook: “first actual case of bug being found.”","22 years later, a computer with 4 KB of memory lands two men on the Moon."],
q:"The Apollo computer had 4 KB. Your phone has millions of times more. So what actually matters — power, or engineering?",
ex:[{t:"Everything is switches",pts:["A computer is billions of tiny on/off switches","ON = 1, OFF = 0 — that's binary","8 bits = 1 byte; bytes build everything","Every photo, password & playlist = a pattern of 1s and 0s"]},
{t:"Counting like a machine",pts:["Each position doubles: 1, 2, 4, 8, 16…","1010 = 8 + 0 + 2 + 0 = ten","Hex packs 4 bits into one symbol (0–9, A–F)","That's why error codes look like A3:5F:9C"]}],
cmp:{t:"Then vs. now",a:["4 KB","Apollo 11 guidance computer, 1969"],b:["~8,000,000 KB","the phone in your pocket"]},
wow:["1202","the error code 26-year-old Steve Bales overruled — and the Eagle landed"],
handoff:"Lab: convert numbers by hand, then find binary hiding in a real ticket.",demo:"binary",
notes:"Pass nothing around yet — keep eyes on screen. Reveal the moth photo story slowly. After the wow slide, run the live binary converter and let the room call out numbers."},

{n:2,title:"What's inside the box",
hook:["1956. IBM ships the world's first hard drive.","It weighs a ton. It moves by forklift.","Companies lease it for thousands a month.","Its capacity: five megabytes. One phone photo wouldn't fit."],
q:"What 'plenty of storage' assumption are we making today that will look ridiculous in 20 years?",
ex:[{t:"The five organs",pts:["CPU — the brain, billions of cycles per second","RAM — fast workspace, erased at power-off","Storage — the long-term memory (HDD/SSD)","Motherboard wires it; the PSU feeds it"]},
{t:"Why turning it off and on works",pts:["RAM forgets everything at power-off","Corrupted working state? Gone","Fresh start, clean slate — that's the whole trick","Now you know WHY the cliché is true"]}],
cmp:{t:"68 years of storage",a:["5 MB · 1,000 kg","IBM RAMAC, 1956 — forklift required"],b:["1,000,000 MB · 0.25 g","a microSD card, today"]},
wow:["×4,000,000,000","improvement in storage per gram since 1956"],
handoff:"Lab: tear a retired PC down to the desk and rebuild it — naming every part.",demo:null,
notes:"Hold up the microSD card AFTER the comparison slide lands, not before. Safety beat: static electricity you can't feel can kill a chip — gloves and wrist straps at the teardown table."},

{n:3,title:"Operating systems — the manager",
hook:["1980. IBM secretly needs an OS for its new PC.","It knocks on the door of a small company: Microsoft.","Microsoft doesn't have one. So it buys 'QDOS' for $75,000…","…and keeps the right to sell it to everyone else. IBM signs."],
q:"IBM thought hardware was the prize. Why was the boring software layer worth trillions?",
ex:[{t:"What an OS actually does",pts:["Referees which program gets the CPU","Hands out memory, talks to devices via drivers","Organizes storage into files & folders","When apps fight, the OS holds the whistle"]},
{t:"The four families you'll support",pts:["Windows — the corporate desktop","macOS — Unix in a tuxedo","Linux — free, runs most of the internet","iOS & Android — the pocket pair"]}],
cmp:{t:"The deal of the century",a:["$75,000","what Microsoft paid for QDOS, 1980"],b:["$3,000,000,000,000+","what that bet became"]},
wow:["1 clause","'we can license it to others' — the sentence that built an industry"],
handoff:"Lab: break a virtual machine on purpose. Snapshots make mistakes free.",demo:null,
notes:"Demo Task Manager live on the projector: find the heaviest process in the room's own machine. The VM snapshot concept is the safety net for the whole course — sell it hard."},

{n:4,title:"Software & the bug that wasn't",
hook:["For decades, programmers saved memory by storing years as 2 digits.","'99' meant 1999. Cheap. Clever. Fine.","Then someone asked: what happens at midnight, Jan 1, 2000?","The world spent half a trillion dollars finding out — before it happened."],
q:"Nothing failed on Jan 1, 2000. Does that prove Y2K was overhyped… or that the fix worked?",
ex:[{t:"The software lifecycle you'll manage",pts:["Install — store, vendor, or company tools","Update — most 'weird behavior' ends here","Repair — fix files without losing settings","Uninstall — cleanly, leftovers cause tickets"]},
{t:"Licenses: the lawyer slide (fun version)",pts:["Proprietary — pay per seat or month","Open source — free to use AND change","Freeware — free but locked","Companies get sued over this. Really."]}],
cmp:{t:"The cost of 2 bytes",a:["2 bytes saved","per date, 1960s–90s"],b:["$300–600 billion","spent fixing it before midnight"]},
wow:["0 planes","fell out of the sky — the most expensive nothing in history"],
handoff:"Lab: install, break, repair and remove an app in your snapshot-protected VM.",demo:null,
notes:"Y2K is the slide about invisible success — connect it to IT's eternal PR problem: when we're perfect, nobody notices. Ask who in the room remembers Y2K news."},

{n:5,title:"Thinking in logic",
hook:["1999. NASA's Mars Climate Orbiter approaches the red planet.","One team's software speaks pound-seconds.","The other team's software expects newton-seconds.","Nothing checks. $327 million becomes a streak in the Martian sky."],
q:"No one at NASA was stupid. So what actually failed — and what check would have caught it?",
ex:[{t:"All software is three moves",pts:["Sequence — do steps in order","Selection — IF this THEN that ELSE other","Iteration — repeat WHILE true","That's it. Everything else is decoration."]},
{t:"Read code like a mechanic",pts:["Rectangles = actions, diamonds = decisions","Variables = labeled boxes holding values","Compiled = translated once, runs fast","Interpreted = read live, easy to tinker"]}],
cmp:{t:"Two famous logic failures",a:["$327M","Mars orbiter — a unit mismatch"],b:["$440M in 45 min","Knight Capital — old code left running"]},
wow:["15 lines","of pseudocode can describe your whole password-reset process. Prove it today."],
handoff:"Lab: pseudocode a real support workflow — your partner must follow it LITERALLY.",demo:null,
notes:"The partner-follows-literally exercise is the punchline: ambiguity becomes hilarious and the lesson teaches itself. Budget 15 minutes for it."},

{n:6,title:"Databases — where the truth lives",
hook:["1998. Pixar. Someone runs a delete command on the wrong directory.","Toy Story 2 starts vanishing — Woody first.","No problem: restore from backup. The backups… are broken.","The film survives on one employee's home computer, driven back wrapped in blankets."],
q:"'We have backups' and 'we have TESTED restores' — what's the difference, and which one saved the movie?",
ex:[{t:"Tables: data with manners",pts:["Rows = records, columns = attributes","A primary key gives each row a name","Tables link by keys — no duplicate chaos","That's 'relational' — 50 years old, still king"]},
{t:"SQL: one verb to rule them",pts:["SELECT name FROM employees WHERE team='Support'","WHERE filters, ORDER BY sorts","Behind every app you fix… is a database","Reading data confidently = quiet superpower"]}],
cmp:{t:"What actually saved Toy Story 2",a:["The official backups","broken — and nobody had checked"],b:["A copy at home","one technical director on parental leave"]},
wow:["1 home PC","stood between the world and no Toy Story 2"],
handoff:"Lab: SQLBolt in the browser — you'll write real queries within 20 minutes.",demo:null,
notes:"Tell the blanket-wrapped-computer detail — it's the image people keep. Then pivot: where does OUR company's truth live, and who tests OUR restores? (Tease Week 26.)"},

{n:7,title:"Networks — how machines talk",
hook:["October 29, 1969. UCLA tries to send one word to Stanford: LOGIN.","L… arrives. O… arrives.","Then the system crashes.","The first message ever sent on the internet's ancestor: 'LO'."],
q:"The network was DESIGNED to survive failures. How does that 1969 decision still shape your job?",
ex:[{t:"The boxes users call 'the router'",pts:["Modem — translates the ISP's signal","Router — decides where traffic goes","Switch — multiplies wired ports","Access point — broadcasts the Wi-Fi"]},
{t:"How a device joins the party",pts:["DHCP hands it an IP address automatically","DNS turns names into addresses","Gateway = the door to everywhere else","No address? No party. (Remember 169.254…)"]}],
cmp:{t:"From two letters to everything",a:["'LO'","total internet traffic, Oct 29 1969"],b:["5+ billion people","online today"]},
wow:["1 hour","later they fixed it and sent the rest — history's first network troubleshooting session"],
handoff:"Lab: map every box and cable in your home or office network.",demo:null,
notes:"'Lo and behold' gets a laugh — use it. Whiteboard the modem→router→switch→AP chain live; most of the room has only ever seen the one combo box."},

{n:8,title:"Security — humans are the firewall",
hook:["May 2000. An email lands in millions of inboxes.","Subject: ILOVEYOU.","Tens of millions of people open it. It eats their files and mails their friends.","Meanwhile, history's most famous hacker barely writes code. Kevin Mitnick just… calls people."],
q:"Honestly: on a busy Tuesday, which gets you — the attachment, or the convincing phone call?",
ex:[{t:"The CIA triad (not that CIA)",pts:["Confidentiality — right eyes only","Integrity — nobody tampered with it","Availability — it works when needed","Every security control protects one of these"]},
{t:"Your daily threat lineup",pts:["Phishing — urgent emails harvesting logins","Malware — viruses, worms, ransomware","Social engineering — hacking the human","Help desks are prime targets. You reset passwords."]}],
cmp:{t:"Which password survives?",a:["P@ssw0rd1","cracked in minutes — rituals don't help"],b:["Tricycle-Mango-87-Lamp","centuries — length & randomness win"]},
wow:["~$10B","damage from one love letter written by one student in Manila"],
handoff:"Lab: 12 real emails on screen — genuine or fraud? Defend every call.",demo:"password",
notes:"Run the live password-strength demo with volunteer (fake!) passwords. Land the uncomfortable truth: attackers target support staff specifically because WE hold the reset keys."},

{n:9,title:"The cloud & the method",
hook:["February 2017. An AWS engineer runs a routine fix.","One parameter is mistyped.","A chunk of the internet goes dark for four hours.","Amazon's own status page can't turn red — its icons live in the service that's down."],
q:"When 'the cloud' fails… what physically failed, and where is it?",
ex:[{t:"The cloud = someone else's computer",pts:["Virtualization: one machine pretends to be many","Snapshots: break things, rewind, repeat","IaaS rent machines · PaaS rent platforms · SaaS rent apps","Your webmail is SaaS. You've used cloud for years."]},
{t:"The 6-step method (your new religion)",pts:["1 Identify — what changed? 2 Theorize","3 Test the theory · 4 Fix it","5 Verify EVERYTHING works · 6 Document","From today, labs grade the method, not luck"]}],
cmp:{t:"Where apps live",a:["On-premises","your server room, your problem"],b:["Cloud","their data center, your status page"]},
wow:["1 typo","took down a measurable slice of the internet for 4 hours"],
handoff:"Lab: a broken VM, the six steps, and you — narrating every move.",demo:null,
notes:"Make the room chant the six steps. Seriously — call and response. They'll roll their eyes and remember it forever, which is the point."},

{n:10,title:"Phase 1 finale — story trivia & the gate",
hook:["Ten weeks ago, most of this room had never opened a computer.","Since then: a moth, a forklift, a $75k deal, a love letter, a typo…","Every story was secretly an exam topic.","Tonight, the stories fight back. Team trivia — then the gate."],
q:"Which Phase 1 story will actually change what you DO at work — and what's the new behavior?",
ex:[{t:"What the gate looks like",pts:["30 questions · 45 minutes · 70% to pass","One retake allowed after 7 days","Practical: user, app, IP, Event Viewer — narrated","Pass = Phase 2 and real hardware"]},
{t:"How to review like a pro",pts:["One practice test COLD → list your misses","Re-study ONLY the misses","Second test confirms the patch","Then sleep. Seriously."]}],
cmp:{t:"Exam-night math",a:["Exhausted 95% brain","cramming until 2 a.m."],b:["Rested 85% brain","wins every time"]},
wow:["10 stories","you now own forever — and each one is an answer"],
handoff:"This week: trivia, the gate, and the practical. Phase 2 awaits.",demo:null,
notes:"Run trivia in teams of 3 with the Phase 1 stories as questions. Keep the energy celebratory — the gate should feel like a boss level, not a threat."},

{n:11,title:"RAM, CPUs & power",
hook:["1994. A math professor checks his Pentium's arithmetic.","Sometimes… division is wrong.","Intel: 'an average user hits it once in 27,000 years.'","The internet disagrees. IBM halts sales. The recall: $475 million."],
q:"Intel was arguably right about the math — and still lost. What did they misjudge?",
ex:[{t:"Memory: the rules",pts:["Desktops take DIMMs, laptops SODIMMs","DDR4 ≠ DDR5 — keyed, never interchangeable","Matched pairs unlock dual-channel speed","Won't boot after upgrade? Reseat. It's seating."]},
{t:"CPUs & power: the gotchas",pts:["Intel & AMD sockets don't mix — check first","No thermal paste = throttle or shutdown","PSU connectors are keyed: 24-pin, 8-pin, SATA","A dying PSU imitates EVERY other failure"]}],
cmp:{t:"The cost of dismissing users",a:["'Once in 27,000 years'","Intel's first answer"],b:["$475,000,000","Intel's final answer"]},
wow:["3 beeps","at power-on is the machine literally telling you which organ hurts"],
handoff:"Lab: teardown #2 — reseat RAM, storage, PSU. Then tour 1,000 BIOS screens in the simulator.",demo:null,
notes:"Play a beep-code sound if you can — the room should hear what 'RAM failure' sounds like. The Lenovo BIOS simulator on the big screen is shockingly fun: take requests."},

{n:12,title:"Storage & the great clone",
hook:["Early 2000s. Motherboards worldwide start dying the same death.","The clue is visual: capacitors bulging like tiny soda cans.","The cause: a stolen electrolyte formula… stolen INCOMPLETE.","For years, techs diagnose it on sight. 'Check the caps' enters the language."],
q:"Thousands of 'random' failures, one bad ingredient upstream. What does that teach about identical machines failing?",
ex:[{t:"The storage ladder",pts:["HDD — spinning platters, cheap, fragile","SATA SSD — no moving parts, ~5× faster feel","NVMe — plugs into the board, multiples faster again","The clicking sound of death is real. Back up first."]},
{t:"Drives that warn you",pts:["SMART = the drive's own health report","Heed it. Drives rarely bluff.","RAID is redundancy — NOT backup","Cooling: front in, back out, dust = blanket"]}],
cmp:{t:"The £0 upgrade users call magic",a:["Old HDD","2-minute boot, constant grinding"],b:["Same PC + SSD","'Did you buy me a new computer?'"]},
wow:["~13×","faster: NVMe vs the hard drive it replaced"],
handoff:"Lab: clone a retired machine's HDD to SSD — time the boot before and after.",demo:null,
notes:"The before/after boot stopwatch is theatre — have two machines racing on screen if possible. Mention the clicking-drive audio cue; once heard, never forgotten."},

{n:13,title:"Printers — know thy enemy",
hook:["1999. The film Office Space.","Three office workers drag a printer to a field…","…and beat it with a baseball bat. Audiences cheer.","The error that inspired it is real: 'PC LOAD LETTER.'"],
q:"'PC LOAD LETTER' was technically ACCURATE — and useless. What makes an error message good?",
ex:[{t:"Laser printing in one breath",pts:["Charge → expose → develop → transfer → FUSE","Smears when touched? The fuser isn't heating","Marks repeating down the page? A roller — spacing names it","Ghost images? Cleaning step failed"]},
{t:"The rest of the zoo",pts:["Inkjets clog when idle — run the clean cycle","Thermal printers: right paper, fades in heat","Queues jam: clear the stuck job first","Cable → driver → device. Cheapest theory first."]}],
cmp:{t:"Error message hall of fame/shame",a:["'PC LOAD LETTER'","accurate, useless, immortal"],b:["'Tray 2 is out of A4 paper'","same fact, zero rage"]},
wow:["#1","most-hated office device, every survey, every year — and your easiest hero moment"],
handoff:"Lab: the lab printer has two sabotaged faults. Fix both, method narrated.",demo:null,
notes:"Show the Office Space clip if your room allows it (30 seconds, fair-use discussion). The repeat-interval-identifies-the-roller trick genuinely impresses — demo with a marked page."},

{n:14,title:"TCP/IP & the doors called ports",
hook:["October 4, 2021. Facebook pushes a routing update.","Facebook, Instagram & WhatsApp vanish from the internet. Six hours.","Engineers rush to fix it — and reportedly can't badge into their own buildings.","The door system lived on the network that was down."],
q:"What's the lesson about keeping a separate back door — and about one network holding ALL the eggs?",
ex:[{t:"Two ways to ship data",pts:["TCP — reliable, ordered, confirmed (web, email)","UDP — fast, no guarantees (calls, games, DNS)","Choose certainty or choose speed","The internet runs on both, constantly"]},
{t:"Ports: numbered doors",pts:["80 web · 443 secure web · 53 DNS","22 SSH · 3389 remote desktop · 445 file share","An app listens on its door number","Memorize the core set — it becomes reflex"]}],
cmp:{t:"Private vs public addresses",a:["192.168.x.x","your house number, behind NAT"],b:["One public IP","the street address everyone shares"]},
wow:["6 hours","the world's biggest social network spent locked out of itself"],
handoff:"Lab: ports tournament, then whiteboard one web request end-to-end.",demo:"ports",
notes:"Run the live ports quiz widget as a class game — fastest hand wins. The 169.254 'nobody answered me' address is the single most useful diagnostic fact of the month."},

{n:15,title:"Small networks & your first war story",
hook:["Tonight's story isn't from a book.","One of OUR IT mentors takes the floor.","A real outage. A real first wrong theory. A real fix.","Take notes — their war story is the prequel to yours."],
q:"What was the first WRONG theory in the mentor's story — and what evidence finally killed it?",
ex:[{t:"The SOHO setup ritual",pts:["FIRST: change the default admin password","SSID + WPA2/WPA3 + strong passphrase","Set the DHCP scope, update firmware","Guest network ON, WPS OFF"]},
{t:"Shadowing starts now",pts:["1 hour with IT every two weeks","Watch twice, then drive supervised","3 signed-off tickets before the Core 2 gate","These hours are the bridge to the job"]}],
cmp:{t:"The #1 home-network hole",a:["admin / admin","factory credentials, still everywhere"],b:["Changed on day one","the 30-second fix that matters most"]},
wow:["3 tickets","stand between you and 'has real experience' on a resume"],
handoff:"Lab: factory-reset the lab router and build a secure network from the checklist.",demo:null,
notes:"Brief your mentor speaker to include the embarrassing wrong turn — that's the teachable part. Book everyone's first shadowing hour before they leave the room."},

{n:16,title:"Mobile devices",
hook:["2016. Samsung launches the Galaxy Note 7.","Then the phones start catching fire.","Airlines ban it BY NAME in pre-flight announcements.","Two recalls later, the product is dead — and battery chemistry is dinner conversation."],
q:"A user hands you a phone with a bulging back. Your answer, in exactly two sentences?",
ex:[{t:"Laptops: what you can actually fix",pts:["RAM (SODIMM), storage, battery, keyboard, screen","Beyond that: vendor-service territory","Batteries age in charge cycles","Swollen battery = stop. Fire risk. No debate."]},
{t:"Phones & MDM",pts:["Corporate email: platform account settings","Triage: airplane toggle → forget/rejoin → updates","MDM enforces passcodes, pushes apps, remote-wipes","Explaining what MDM can't see = trust gold"]}],
cmp:{t:"Battery states",a:["Flat & healthy","normal aging, replace at leisure"],b:["Bulging","a slow-motion fire. Today's problem."]},
wow:["2 recalls","of the same phone — the second for the 'fixed' replacements"],
handoff:"Lab: laptop RAM/storage swap + corporate email on the Android emulator.",demo:null,
notes:"If you can source a (safely depleted) swollen battery photo set, show it — recognition saves fires. Practice the calm two-sentence script as a room."},

{n:17,title:"Virtualization & the chaos monkey",
hook:["2008. A database failure stops Netflix shipping DVDs for three days.","Leadership's radical conclusion: we shouldn't OWN data centers.","Eight years of migration to the cloud follow.","Then they build a tool that randomly kills their own servers. On purpose. In production."],
q:"Netflix deliberately breaks itself so failures stay boring. Why is that brave engineering, not madness?",
ex:[{t:"Hypervisors: the landlords",pts:["Type 1 — directly on server metal (ESXi, Hyper-V)","Type 2 — an app on your desktop (VirtualBox)","Host = the real machine, guests = the VMs","Overcommit RAM and every tenant suffers"]},
{t:"Cloud models = who manages what",pts:["IaaS — you rent machines (Azure VMs)","PaaS — you bring code, they run the platform","SaaS — you just use the app (M365)","'The app is slow' often = check the status page"]}],
cmp:{t:"Two responses to failure",a:["Hope it won't recur","the default plan everywhere"],b:["Chaos Monkey","break yourself daily until failure is boring"]},
wow:["8 years","to move one company to the cloud — migrations are marathons"],
handoff:"Lab: two VMs, one host, deliberately starve them of RAM — watch the suffering live.",demo:null,
notes:"The overcommit demo is visceral on a projector: open Task Manager on the host while both guests crawl. Connect SaaS to the tools this company already lives in."},

{n:18,title:"Troubleshooting under fire",
hook:["A university department files a serious ticket:","'We can only send email about 500 miles.'","Obviously impossible. Obviously nonsense.","Except… a timeout was set so short that, at the speed of light, farther servers couldn't answer in time. The users were RIGHT."],
q:"What's the most 'impossible' symptom a customer ever gave you — and what if it was literally true?",
ex:[{t:"The big three, with opening moves",pts:["No power → outlet → PSU switch → power button","No POST → beep codes → reseat RAM → minimal boot","No boot device → boot order → cables → THEN panic","Cheapest theory always goes first"]},
{t:"Network triage, bottom-up",pts:["Link lights → does the cable even live?","ipconfig → real address or 169.254?","ping the gateway → ping 8.8.8.8 → ping a NAME","First failure marks the floor of the problem"]}],
cmp:{t:"Two technicians",a:["The shotgunner","swaps parts until something works"],b:["The methodist","narrates, isolates, and KNOWS why it's fixed"]},
wow:["~500 miles","how far light travels in the misconfigured timeout. The users measured physics."],
handoff:"Lab: three sabotaged stations, 20 minutes each, method narrated and scored.",demo:null,
notes:"Tell the 500-mile story slowly — it's the best troubleshooting parable ever written. The stations week is loud and fun; sabotage list is in the instructor pack."},

{n:19,title:"Core 1 gate",
hook:["Nine weeks of hardware, networks, mobile and cloud.","A recall, a plague, a printer in a field, a locked-out giant…","Today the stories warm you up —","— and the gate decides who's a hardware tech now."],
q:"Which Core 1 topic still feels shaky? Saying it out loud IS the last-hour review list.",
ex:[{t:"Today's format",pts:["Trivia warm-up: Phase 2 stories so far","20 questions · 35 minutes · 70%","Timed practical: sabotaged machine → working desktop","Narrate the method — it's what's graded"]},
{t:"Exam-craft",pts:["'MOST likely cause' = the cheapest theory","'Check FIRST' = the simplest step","Eliminate two wrong answers, odds double","Flag, move on, return — never stall"]}],
cmp:{t:"Question logic",a:["'Replace the motherboard'","expensive, dramatic, usually wrong"],b:["'Reseat the RAM'","boring, cheap, usually right"]},
wow:["70%","the bar. You've cleared it in practice — now do it once for real."],
handoff:"Gate + practical today. Core 2 (the software side) starts next week.",demo:null,
notes:"Keep gate day light: trivia first, snacks if you can. Anyone who misses the bar gets the 7-day retake plan privately and kindly — attrition handled with dignity."},

{n:20,title:"Windows: users & permissions",
hook:["April 1998. Bill Gates on stage, world's press watching.","An assistant plugs in a scanner to show off plug-and-play.","The machine blue-screens. Instantly. In front of everyone.","The recovery line — 'that must be why we're not shipping Windows 98 yet' — gets the biggest laugh of the show."],
q:"Your fix fails IN FRONT of the user. What do you say in the first ten seconds?",
ex:[{t:"Accounts: two species",pts:["Local — lives on one machine","Domain — managed centrally by Active Directory","Corporate life = domain life","Most of your future tickets touch AD"]},
{t:"Permission rules to tattoo",pts:["NTFS permissions are CUMULATIVE — most generous group wins","…except explicit DENY beats everything","Over the network: stricter of share vs NTFS wins","UAC is annoying because it's the wall"]}],
cmp:{t:"Who can read the folder?",a:["Group A: Read","Group B: Modify → user gets Modify"],b:["+ explicit Deny","user gets nothing. Deny always wins."]},
wow:["1 laugh","turned a global humiliation into a human moment. Composure is a skill."],
handoff:"Lab: build a 3-user permission scheme, then PROVE who sees what.",demo:null,
notes:"Roleplay the failed-fix moment in pairs — ten seconds of composure practice. Then live-demo cumulative permissions; the explicit-Deny reveal lands like a plot twist."},

{n:21,title:"The command line",
hook:["A sysadmin's confession goes viral:","Over years, he scripted his ENTIRE job.","Scripts watched servers, fixed failures, replied to email…","…one even texted his wife 'late at work' if his session ran past 9pm."],
q:"If a script does the work… who's responsible when it does the work WRONG?",
ex:[{t:"Commands that close tickets",pts:["ipconfig /all — who am I? · /flushdns — forget bad lookups","sfc /scannow — repair Windows itself","chkdsk — disk health · gpupdate — fresh policy","Each one faster than its GUI — and works when the GUI won't"]},
{t:"Two shells, one machine",pts:["cmd — the classic, still everywhere","PowerShell — Verb-Noun: Get-Process, Restart-Service","The pipe | feeds one command into the next","Today you stop fearing the blinking cursor"]}],
cmp:{t:"Restarting one service on 100 PCs",a:["GUI route","100 machines × many clicks × all afternoon"],b:["One PowerShell line","seconds. This is why CLI exists."]},
wow:["12 answers","in today's scavenger hunt that the GUI literally cannot give you"],
handoff:"Lab: the CLI scavenger hunt — raced in pairs, winners brag forever.",demo:null,
notes:"Demo sfc /scannow live at the start (it takes a while — perfect background theatre). The hunt is competitive by design; rivalry is a memory aid."},

{n:22,title:"Linux & macOS",
hook:["August 25, 1991. A Finnish student posts to a newsgroup:","'I'm doing a (free) operating system —","just a hobby, won't be big and professional.'","His name is Linus. The hobby now runs most of the internet."],
q:"He gave it away for free — and that's exactly why it won. Why does free-and-open beat owned-and-sold for infrastructure?",
ex:[{t:"Terminal survival kit",pts:["ls, cd, pwd — look, move, locate","cp, mv, rm — copy, move, delete (NO recycle bin)","sudo — do as admin · apt install — get software","chmod — permissions, the rwx triplets"]},
{t:"macOS: Unix in a tuxedo",pts:["Same terminal language as Linux — skills transfer 1:1","Time Machine = backup · Keychain = passwords","Cmd-Space finds anything · Cmd-Opt-Esc force-quits","One skillset now covers three desktops"]}],
cmp:{t:"Where the OSes actually run",a:["Desktops","Windows dominates the office"],b:["Servers & phones","Linux runs the internet — and every Android"]},
wow:["100%","of the world's top 500 supercomputers run the 'hobby'"],
handoff:"Lab: Ubuntu VM — make a user, install software, lock a secret file, prove it.",demo:null,
notes:"Show the actual 1991 Usenet post on screen — it's charmingly modest. Webminal for homework means zero install excuses."},

{n:23,title:"Malware & the $10 kill switch",
hook:["May 12, 2017. WannaCry tears across the planet.","Hospitals cancel surgeries. Factories stop. Hundreds of thousands of machines, one day.","A 22-year-old researcher notices the malware checks a nonsense web domain…","…registers it for about $10 to study the traffic — and accidentally hits the kill switch."],
q:"The patch existed for TWO MONTHS before WannaCry. Why don't organizations patch — and what would change that?",
ex:[{t:"Know your enemy by behavior",pts:["Virus rides files · Worm spreads itself","Trojan pretends to be friendly software","Ransomware encrypts & extorts","Rootkits hide deep and lie to the OS"]},
{t:"The removal ritual (ORDER MATTERS)",pts:["Identify → QUARANTINE (pull the network)","Disable System Restore — don't preserve infection","Update definitions FIRST, then scan","Educate the user — step 6 prevents the sequel"]}],
cmp:{t:"Two costs",a:["~$10","price of the domain that stopped it"],b:["$4+ billion","estimated global damage it caused first"]},
wow:["2 months","the fix sat available before the disaster. Patching is the whole game."],
handoff:"Lab: a deliberately infected VM, the formal procedure, your steady hands.",demo:null,
notes:"Marcus Hutchins' arc (accidental hero, complicated past, redemption) is worth one extra minute — the room will Google him anyway. Drill WHY definitions update first."},

{n:24,title:"Hardening & the HVAC contractor",
hook:["Late 2013. Attackers steal ~40 million card numbers from Target.","The way in wasn't the payment system.","It was the heating-and-air-conditioning contractor's stolen login.","From the air conditioning… to every cash register in America."],
q:"List everyone who is 'inside' your company's network. Now — who did you forget?",
ex:[{t:"Least privilege: the spine",pts:["Every account gets EXACTLY what its role needs","Nobody browses the web as admin","'Just give them full access' is never the fix","Breaches travel on excess permission"]},
{t:"The 10-minute hardening pass",pts:["Updates automatic · Defender/EDR on","BitLocker — a stolen laptop becomes a brick","Screen lock, firewall, unused services off","MFA: two DIFFERENT kinds of proof"]}],
cmp:{t:"Two security models",a:["Castle & moat","hard outside, soft chewy inside"],b:["Zero trust","verify everyone, everywhere, always"]},
wow:["40,000,000","card numbers — via the air conditioning vendor"],
handoff:"Lab: harden a fresh VM to the checklist, then audit your partner's.",demo:null,
notes:"The 'who did you forget' question deserves real silence — vendors, printers, the coffee machine with Wi-Fi. Peer-audit creates healthy paranoia; reward the pickiest auditor."},

{n:25,title:"When software breaks the world",
hook:["July 19, 2024. A security vendor pushes a routine update.","Within hours: 8.5 MILLION Windows machines blue-screen.","Flights ground. Hospitals postpone. Broadcasters go dark.","There is no remote fix. Every machine needs hands on a keyboard — and the hands belong to people like you."],
q:"Same outage, different companies: some back in hours, some in weeks. What separated them?",
ex:[{t:"The boot-repair ladder",pts:["Three failed boots → auto-repair offers itself","WinRE → Startup Repair → System Restore","Safe mode boots? Suspect a driver or startup app","bootrec fixes the boot record — last rungs first? Never."]},
{t:"Crashes leave fingerprints",pts:["Event Viewer → Windows Logs → Application","The Error entry NAMES the faulting module","Fix sequence: update → repair → cache → reinstall","Antivirus conflicts: the repeat offender"]}],
cmp:{t:"July 19, 2024 by the numbers",a:["1 file","the faulty update at the center"],b:["8,500,000","machines fixed one safe-mode boot at a time"]},
wow:["The heroes","of the largest IT outage in history were support technicians. This job."],
handoff:"Lab: a no-boot VM and a crashing app — Event Viewer evidence required in your write-up.",demo:null,
notes:"This is the motivational centerpiece of the whole program — these trainees are studying to BE the people who fixed July 19th. Let that land before the ladder mechanics."},

{n:26,title:"Documentation & the server in Ghana",
hook:["June 2017. NotPetya detonates inside shipping giant Maersk.","49,000 laptops dead. Thousands of servers. Every copy of the company directory…","…except ONE domain controller in Ghana — offline that day because of a power cut.","They fly its disk to the UK and rebuild a global company from it in ten days."],
q:"Maersk survived by ACCIDENT. Design the on-purpose version: what's offline, where, how often?",
ex:[{t:"A closure note has four parts",pts:["The problem as reported","The actual cause found","Steps specific enough to REPEAT","Verification performed. Write for 2 a.m. you."]},
{t:"Change management & 3-2-1",pts:["What, why, when, rollback, approver","Rollback plans are written BEFORE, not during panic","Backups: 3 copies, 2 media, 1 offsite","Restores are TESTED, not assumed (hi, Pixar)"]}],
cmp:{t:"Two closure notes",a:["'Fixed.'","helps no one, ever"],b:["Problem · cause · steps · verified","becomes a knowledge-base article"]},
wow:["10 days","to rebuild a company that runs ~20% of world shipping — from one lucky disk"],
handoff:"Lab: install osTicket yourselves (sneaky Linux lab), then rewrite 3 real tickets properly.",demo:null,
notes:"The power-cut detail is the hook — luck as architecture review. The osTicket install is secretly three labs in one; let them discover that afterward."},

{n:27,title:"Scripting — power tools",
hook:["2015. A bug ships in Steam's Linux uninstaller.","The script reaches: delete everything under \"$STEAMROOT\"/*","But if that variable is ever EMPTY…","…the line becomes: delete everything. Under slash. The whole filesystem. For some users, it did."],
q:"Write the safety check that line needed. (In words is fine.)",
ex:[{t:"Read before you write",pts:[".ps1 PowerShell · .sh Bash · .bat old Windows","Variables hold values · if/else branches · loops repeat","Comments are the author talking to YOU — read them first","Never run a script you haven't read"]},
{t:"PowerShell reads like English",pts:["Get-Process — list what's running","Get-Service spooler | Restart-Service — fix printing","The pipe | chains commands into pipelines","Test in a VM. Echo before you execute."]}],
cmp:{t:"One variable, two outcomes",a:["\"$STEAMROOT\"/*","deletes the Steam folder"],b:["(empty)/*","deletes EVERYTHING. Quote your variables."]},
wow:["1 missing check","between a routine uninstall and a wiped home folder"],
handoff:"Lab: predict three scripts line-by-line, then add the check that would've saved Steam.",demo:null,
notes:"Walk the Steam line on screen character by character — the room should gasp at the moment the variable empties. 'Scripts multiply whatever you feed them' is the tattoo line."},

{n:28,title:"Core 2 gate — the gauntlet",
hook:["The on-stage blue screen. The hobby that ate the world.","The $10 kill switch. The HVAC contractor. The weekend 8.5 million machines came back.","Every story is now reflex.","Three stations. One clock. Narrate everything."],
q:"Of everything in Phase 2 — what will you actually do DIFFERENTLY at work on Monday?",
ex:[{t:"Today",pts:["20 questions · 35 minutes · 70%","Station 1: hardware fault → boot","Station 2: network fault → internet","Station 3: crashing app → Event Viewer evidence"]},
{t:"Also due",pts:["3 supervised tickets signed off by your mentor","That's real, logged experience","Pass today = A+-level technician, in skills terms","Phase 3 builds the network specialist on top"]}],
cmp:{t:"What today certifies",a:["Week 11 you","could reseat RAM, nervously"],b:["Today you","diagnose hardware, OS & malware — with a method"]},
wow:["3 × 20 min","stations between you and Phase 3. The stories did the studying with you."],
handoff:"Gauntlet today. Networking — the OSI model and beyond — next week.",demo:null,
notes:"Same gate-day playbook: warm, celebratory, snacks. Privately schedule retakes where needed. Photograph the cohort — Phase 3 starts a new chapter."},

{n:29,title:"The OSI model — the map",
hook:["October 21, 2016. Twitter, Netflix, Reddit and Spotify all vanish.","The attacker? An army of hacked home webcams and DVRs —","— still running their factory passwords.","The internet was taken down by security cameras nobody secured."],
q:"Walk the webcam army up the OSI layers. Where could it have been stopped — and by whom?",
ex:[{t:"Seven layers, one map",pts:["L1 cables · L2 switches & MACs · L3 routers & IPs","L4 TCP/UDP & ports · L7 the apps themselves","'Layer 1 problem' = professional for 'check the cable'","Every network conversation uses this map"]},
{t:"Encapsulation: the nesting dolls",pts:["Data → wrapped in a TCP segment","→ inside an IP packet → inside an Ethernet frame","Unwrapped in reverse at the far end","Switch reads frames (L2), router reads packets (L3)"]}],
cmp:{t:"Switch vs router",a:["Switch · Layer 2","forwards by MAC, inside one network"],b:["Router · Layer 3","forwards by IP, BETWEEN networks"]},
wow:["100,000+","hijacked cameras in the Mirai army. Change. Default. Passwords."],
handoff:"Lab: 30 technologies, 7 layers, sort and defend your placements.",demo:"osi",
notes:"Run the animated packet-through-the-layers demo twice: once narrated by you, once narrated by a volunteer. The layer-sort card game gets loud — that's correct."},

{n:30,title:"Wireshark — reading the network's mind",
hook:["Every mystery in this phase ends the same way:","somebody looks at the packets.","Not what users felt. Not what dashboards summarized.","What actually crossed the wire — byte by byte. Today, you learn to read the flight recorder."],
q:"'The website is slow.' What can a 60-second capture tell you that an hour of guessing can't?",
ex:[{t:"Capture survival",pts:["Right interface, then filters: http, dns, ip.addr==…","Follow → TCP Stream = read one conversation","Color rules: the screen triages for you","Lab networks or written authorization ONLY"]},
{t:"Three patterns to know on sight",pts:["SYN → SYN/ACK → ACK: a connection being born","SYN with no answer: blocked or dead","DNS query/answer: the name-to-number moment","HTTP 200 OK · 404 missing · 500 their fault"]}],
cmp:{t:"Two versions of the truth",a:["'It's slow sometimes'","the ticket"],b:["3 retransmits + 2s DNS delay","the capture"]},
wow:["3 packets","SYN, SYN/ACK, ACK — the handshake that starts every connection you've ever made"],
handoff:"Lab: load one webpage, then find its DNS lookup, handshake and status code in your capture.",demo:null,
notes:"Capture the room's own page-load live on the projector — seeing 'their' traffic appear is the magic moment. State the ethics rule plainly and once."},

{n:31,title:"Subnetting I — the address math",
hook:["February 3, 2011. A small ceremony in Miami.","The last free blocks of IPv4 addresses are handed out.","4.3 billion addresses — which 1981 engineers called 'effectively infinite' — gone.","Since then, internet addresses trade like real estate."],
q:"What 'effectively infinite' resource are we under-budgeting RIGHT NOW?",
ex:[{t:"The anatomy",pts:["IPv4 = 32 bits, four octets: 192.168.10.45","The mask splits network bits from host bits","/24 = 255.255.255.0 = 254 usable hosts","Network address: hosts all-0 · broadcast: all-1"]},
{t:"Powers of two = your times tables",pts:["/25→126 · /26→62 · /27→30 · /28→14","Each borrowed bit: half the hosts, double the subnets","IPv6 ends scarcity: 2001:db8::1 (:: squeezes zeros)","Drill 20 today, 20 tomorrow. Repetition wins."]}],
cmp:{t:"Address space",a:["IPv4: 4.3 billion","exhausted, traded, NAT-stretched"],b:["IPv6: 340 undecillion","every grain of sand can have trillions"]},
wow:["$7,500,000","what Microsoft paid for one bankrupt company's IPv4 block"],
handoff:"Lab: 20 subnetting drills, then whiteboard the two hardest as a room.",demo:"subnet",
notes:"Run the live subnet calculator: the room shouts an address+mask, the screen shows network/broadcast/range with working. Then they do it by hand — calculator privileges are earned."},

{n:32,title:"Subnetting II — designing with it",
hook:["When Nortel went bankrupt, lawyers inventoried the assets.","Buildings, patents… and a forgotten pile of IPv4 addresses.","Microsoft paid $7.5 million for the block.","Yesterday's homework math prices in millions. Today you design with it."],
q:"Your design must survive the company DOUBLING. Where's the headroom, and what does it cost today?",
ex:[{t:"Design inputs",pts:["How many subnets? (one per department/zone)","How many hosts each? Then DOUBLE it","Size to the next power of two","Clean boundaries: .10.0 staff, .20.0 guests, .30.0 servers"]},
{t:"Conventions that save future-you",pts:["Gateways always .1 — no exceptions","Servers in a reserved low range","DHCP scopes leave static room","WRITE IT DOWN. Undocumented plans cause outages."]}],
cmp:{t:"Two address plans",a:["One flat /16","everything everywhere, no map"],b:["Designed subnets","readable at a glance, defensible by zone"]},
wow:["×2","the growth your plan must absorb without redesign. Headroom is cheap today, brutal later."],
handoff:"Lab: full addressing plan for a 3-department office — then peers attack it.",demo:null,
notes:"The peer-attack review is the actual lesson: defending boundaries out loud cements the logic. Praise clean, boring, readable plans over clever ones."},

{n:33,title:"Switching & VLANs",
hook:["November 2002. Boston's Beth Israel hospital.","The network drowns — in its OWN traffic.","A switching loop: frames circulating endlessly, multiplying.","For days, doctors use paper charts. Runners carry lab results through corridors."],
q:"Why does a healthy network NEED a protocol whose entire job is turning connections OFF?",
ex:[{t:"Switches & VLANs",pts:["A switch learns which MAC lives on which port","VLANs slice one switch into separate networks","VLAN 10 can't reach VLAN 20 without a router","Staff, guests, servers — separated on shared metal"]},
{t:"Trunks, loops & STP",pts:["Access port = one VLAN · trunk = many, tagged (802.1Q)","Connect switches in a circle → broadcast storm","Spanning Tree blocks redundant links until needed","Beth Israel is why STP exists in every switch"]}],
cmp:{t:"One switch, two worlds",a:["Flat network","everyone sees everyone — including guests"],b:["VLANs","logical walls, same hardware"]},
wow:["Days on paper","a modern hospital, defeated by frames going in circles"],
handoff:"Lab: two switches, two VLANs, one trunk — prove isolation, then connectivity.",demo:null,
notes:"Draw the loop on the whiteboard and multiply the broadcast by hand — 1, 2, 4, 8 — until the room sees the storm. Packet Tracer makes the fix satisfying."},

{n:34,title:"Routing & the YouTube black hole",
hook:["February 2008. Pakistan orders local ISPs to block YouTube.","Pakistan Telecom announces a more-specific route for YouTube's addresses…","…and the announcement leaks to the whole internet.","The world's routers, trusting as designed, pour YouTube's traffic into Pakistan. Global outage."],
q:"The internet's backbone protocol mostly believes what it's told. What would 'fixing' that cost?",
ex:[{t:"How routers decide",pts:["Routing table: for each destination, which way next","Static — an admin typed it · dynamic — routers gossip","OSPF inside organizations · BGP between them","Default gateway: 'everything else goes HERE'"]},
{t:"NAT — the great stretch",pts:["Your router rewrites private → one public address","Keeps a table to route the replies home","Hundreds of devices, one street number","Port forwarding = a deliberate inbound hole"]}],
cmp:{t:"Wrong gateway symptoms",a:["Can reach neighbors","same-network pings work fine"],b:["Can't reach the world","the door is mislabeled"]},
wow:["~2 hours","the planet's YouTube traffic spent in a black hole — from one leaked route"],
handoff:"Lab: router-on-a-stick joins your VLANs; a static route reaches site two.",demo:null,
notes:"BGP-runs-on-trust is the mind-blower for newcomers — let it breathe. Router-on-a-stick clicks when you draw the subinterfaces as apartment mailboxes on one door."},

{n:35,title:"Wireless — the crowded air",
hook:["For 17 YEARS, a world-class radio telescope in Australia records mystery signals.","Scientists name them 'perytons.' Papers are written.","In 2015, someone finally traces the source:","the observatory kitchen's microwave oven — when staff open the door early."],
q:"How do you PROVE to a skeptical user that interference — not 'bad Wi-Fi' — is the problem?",
ex:[{t:"Two bands, two personalities",pts:["2.4 GHz: travels far, crowded (microwaves, Bluetooth…)","Only channels 1, 6, 11 don't overlap","5 GHz: faster, cleaner, shorter range","6 GHz (Wi-Fi 6E/7): the new open highway"]},
{t:"Security & the survey",pts:["WEP broken → WPA2 floor → WPA3 standard","Enterprise mode: every user authenticated (RADIUS)","Site survey: walk, measure, map the dead zones","Turns Wi-Fi complaints from vibes into data"]}],
cmp:{t:"The 2.4 GHz neighborhood",a:["Your Wi-Fi","sharing the air with…"],b:["Microwaves, Bluetooth, baby monitors","…all shouting at once"]},
wow:["17 years","world-class astronomers defeated by lunch"],
handoff:"Lab: configure the AP properly, then heat-map the floor with a phone analyzer.",demo:null,
notes:"Open a Wi-Fi analyzer live on the projector — the channel graveyard of your own building is the proof. The microwave reveal deserves theatrical timing."},

{n:36,title:"DHCP, DNS & the haiku",
hook:["There is a haiku every network engineer knows by heart:","'It's not DNS.","There's no way it's DNS.","It was DNS.'"],
q:"Why does a DNS failure look like 'the ENTIRE internet is down' — and how do you prove it in 60 seconds?",
ex:[{t:"DHCP: identity in four steps",pts:["Discover → Offer → Request → Acknowledge","You get: address, mask, gateway, DNS — on a lease","Reservations pin devices · exhausted scopes strand them","169.254.x.x = 'nobody answered me'"]},
{t:"DNS: the resolution chain",pts:["Cache → resolver → root → .com → the answer","A = name→IPv4 · CNAME alias · MX mail","The 60-second proof: ping 8.8.8.8 ✓, ping a name ✗","nslookup names the witness. NTP keeps clocks honest."]}],
cmp:{t:"The minute-long diagnosis",a:["ping 8.8.8.8 → works","the internet is fine"],b:["ping google.com → fails","it was DNS. It's always DNS."]},
wow:["Half the web","went dark in 2016 because one DNS provider was attacked. Everything leans on names."],
handoff:"Lab: instructor kills DHCP, then poisons DNS. Find both — evidence first.",demo:null,
notes:"Recite the haiku with gravity; invite an IT mentor to testify with an internal DNS war story. The ping-IP-vs-ping-name proof should become muscle memory tonight."},

{n:37,title:"Network security & the air gap",
hook:["Discovered 2010: malware unlike anything before.","Stuxnet targets the controllers spinning uranium centrifuges —","drives them to destructive speeds while replaying NORMAL readings to the operators.","The facility wasn't even online. The worm walked in on USB drives."],
q:"The target was offline and still got hit. What does 'air-gapped' actually protect against — and where is it theater?",
ex:[{t:"Defense is geometry",pts:["Segment: user VLANs, server VLANs, DMZ for public-facing","Guests & IoT isolated (remember the webcam army)","ACLs guard the borders, top-down, implicit deny","What must talk = the ONLY things that can"]},
{t:"Tunnels & zero trust",pts:["VPN: an encrypted tunnel across untrusted networks","Protects transit — not an infected endpoint","Zero trust: never trust by location, verify always","Assume breach. Design for the day it happens."]}],
cmp:{t:"What the operators saw vs reality",a:["Gauges: all normal","the replayed lie"],b:["Centrifuges: tearing apart","the physical truth"]},
wow:["1 USB stick","is all an 'air gap' takes to cross"],
handoff:"Lab: write the ACL that blocks guests from the server — and prove both directions.",demo:null,
notes:"Stuxnet earns its full two minutes — it reframes what software can DO. Tie back to Target and Mirai: this whole phase has been one argument for segmentation."},

{n:38,title:"Monitoring — seeing the invisible",
hook:["January 15, 1990. One line of code ships to AT&T's switches.","A switch crashes. Its recovery message… crashes its neighbor.","The neighbor recovers — and crashes the next. A wave rolls coast to coast.","Nine hours. Tens of millions of dead calls. The network attacked itself."],
q:"Every light turns red at the same moment. Cascade — or fifty coincidences? How do you tell, and which do you fight first?",
ex:[{t:"The visibility stack",pts:["SNMP polls metrics & receives shouted traps","Syslog centralizes every device's diary","NetFlow: who talks to whom, how much","Uptime checks ping what must answer"]},
{t:"Baselines & alert hygiene",pts:["A baseline = recorded NORMAL","'High' only means something vs usual","Alert on what demands action — or be ignored","Staged rollouts exist because of Jan 15, 1990"]}],
cmp:{t:"A graph without vs with a baseline",a:["'CPU at 60%'","is that bad? Who knows."],b:["'Triple the Tuesday norm'","now it's a diagnosis"]},
wow:["9 hours","one line of code rolled across a continent's phone network"],
handoff:"Lab: guided tour of OUR real monitoring stack — write what YOU'd watch, and why.",demo:null,
notes:"The mentors run this one — real dashboards beat any slide. Push the room on the cascade question; the answer (find the common dependency, fight upstream) is the seed of senior thinking."},

{n:39,title:"The troubleshooter's toolkit",
hook:["2011. A 75-year-old woman in Georgia digs for scrap copper.","Her spade finds a buried fiber-optic cable.","Most of neighboring ARMENIA loses the internet for hours.","The most sophisticated network on Earth answers to a shovel."],
q:"A user says 'the internet is down.' Narrate your first five checks — starting from the spade.",
ex:[{t:"Commands, by the question they answer",pts:["ping — can I reach you? · tracert — where does the path die?","ipconfig /all — who am I? · nslookup — does the name resolve?","arp -a — who's around me? · netstat — who's talking?","Linux: ip a, ip route, dig"]},
{t:"Strategy",pts:["Climb the OSI ladder BOTTOM-UP","Stop at the first failure — above it is symptoms","Change ONE variable per test","Impossible symptom? Remember the 500 miles."]}],
cmp:{t:"Layer 1 humility",a:["Billions in infrastructure","fiber, satellites, data centers"],b:["One spade","hours of national outage"]},
wow:["75","the age of the pensioner who disconnected a country"],
handoff:"Lab: the command relay — 15 symptom cards, name the command and the layer, fastest team wins.",demo:null,
notes:"The babushka story is the perfect closer for methodology: physical first, always. Run the relay loud and timed; the winning team picks next week's trivia category."},

{n:40,title:"The gauntlet",
hook:["Every story this year had one thing in common:","a person at a keyboard, deciding what to check FIRST.","Today the keyboard is yours. Three hidden faults. 45 minutes.","The stories were the training montage. This is the scene."],
q:"Afterward: which fault took longest — and which step of the method would have found it faster?",
ex:[{t:"The rules of the arena",pts:["A prebuilt network, three faults of familiar kinds","Wrong VLAN? Missing gateway? Dead DHCP? Poisoned DNS?","End-to-end connectivity in 45 minutes","Narration mandatory — the method IS the score"]},
{t:"Play it like a professional",pts:["Map what WORKS first — it outlines what doesn't","Bottom-up, one fix per test","Fault interactions LIE if you fix two blind","Keep the running log: it's capstone rehearsal"]}],
cmp:{t:"Two players",a:["The panicker","changes five things, learns nothing"],b:["The professional","one variable, one test, one truth at a time"]},
wow:["45:00","on the clock. You've been training for this since the moth."],
handoff:"Gauntlet today. Mock exam next week. Capstone after. Almost there.",demo:null,
notes:"Mentors observe silently and score narration. Debrief as a group: every gauntlet produces one great story — harvest it for the next cohort's deck."},

{n:41,title:"The story championship & the mock",
hook:["The moth. The forklift. LO. The love letter.","The Pentium. The kill switch. The server in Ghana. The webcams.","The hospital loop. The black hole. The microwave. The spade.","Thirty-six stories — and every single one was an exam objective in costume."],
q:"Pick the ONE story you'll still be telling in ten years. Why that one?",
ex:[{t:"Today",pts:["Team trivia: the full year, every story","Then the mock: 30 questions · 50 minutes · 70%","Real exam conditions: closed book, quiet, no phones","Styled like the real Network+ on purpose"]},
{t:"After the mock",pts:["Miss list → targeted re-study → short re-quiz","Declare your capstone: build-out, defense, or project","Next week has NO decisions left","Only the work — and the finish line"]}],
cmp:{t:"What 41 weeks built",a:["36 stories","you can tell at any dinner"],b:["36 objectives","you can pass in any exam room"]},
wow:["1 week","to graduation"],
handoff:"Trivia, mock, capstone declaration. See you at the finale.",demo:null,
notes:"Make the championship genuinely competitive — prizes, bracket, drama. The mock under real conditions matters: familiarity with the ROOM is half of exam nerves."},

{n:42,title:"Capstone day — their story starts here",
hook:["A surprising number of the people running networks and security today…","…started exactly where this cohort started: answering support calls.","The gap was never talent. It was structured opportunity.","You just spent 42 weeks building one. The next cohort's Week 1 story might be about someone in this room."],
q:"What's the first sentence of the story YOU'LL tell the next cohort?",
ex:[{t:"Today",pts:["Capstones delivered: design, defense, or project","Scored independently by IT manager + program lead","Rubric: accuracy, method, documentation, communication, independence","18 of 25 to pass"]},
{t:"What you leave with",pts:["Certificate + skills transcript from the tracker","A conversation with the IT hiring manager","Exam-ready, if you ever choose the official certs","Proof. The kind that changes job titles."]}],
cmp:{t:"Day 1 vs Day 294",a:["A support rep","curious, capable, uncredentialed"],b:["A technician","with a method, a transcript, and 36 stories"]},
wow:["42 weeks","from the support queue to the server room. Congratulations."],
handoff:"Presentations, certificates, photos. Then: go change your job title.",demo:null,
notes:"Invite managers and the executive sponsor — visibility is the graduates' reward and the program's budget case. End with the Week 1 moth photo on screen. Full circle."}
];
if(typeof module!=='undefined')module.exports=SESSIONS;

/* ===== DETAIL LAYER: small-print facts, diagrams, videos, extra sims =====
   facts: appear in small text after the story's last reveal (HTML) / under the story (PPTX)
   vis:   labeled diagram slide (see diagrams.js) · vid: YouTube ID for an embedded short video
   To add a video: paste just the 11-character ID from any youtube.com/watch?v=XXXXXXXXXXX link. */
const EXTRA={
1:{facts:["The moth logbook page is preserved at the Smithsonian","Apollo AGC: ~4 KB RAM, 72 KB ROM, woven by hand ('rope memory')","Margaret Hamilton's priority-scheduling design is why 1202 was survivable"]},
2:{facts:["IBM RAMAC 305 (1956): 5 MB on fifty 24-inch platters","Lease price: ~$3,200/month — ~$35k in today's money","A 1 TB microSD holds ~200,000 RAMACs"],vis:"pc"},
3:{facts:["QDOS = 'Quick and Dirty Operating System', by Tim Paterson","IBM PC launched Aug 12, 1981 at $1,565","The non-exclusive license let Microsoft sell MS-DOS to every clone maker"]},
4:{facts:["Global Y2K remediation estimate: $300–600 billion","Some failures did occur: a few payment terminals & bus validators glitched","Y2K38 is real: 32-bit Unix time overflows on Jan 19, 2038"]},
5:{facts:["Mars Climate Orbiter lost Sept 23, 1999 — lbf·s vs N·s","Knight Capital, Aug 1, 2012: ~$440M in ~45 minutes","One of Knight's 8 servers missed the deployment — old flag reactivated"]},
6:{facts:["The command was rm -rf on the wrong path","Backups had been silently failing for about a month","Galyn Susman's home machine held the only complete copy"]},
7:{facts:["Oct 29, 1969, 22:30 — UCLA (Kleinrock's lab) → SRI Stanford","ARPANET's design goal: keep working when nodes fail","TCP/IP became the standard on Jan 1, 1983 ('flag day')"],vis:"homenet"},
8:{facts:["ILOVEYOU (May 2000): ~10% of internet-connected PCs in days","Author Onel de Guzman faced no charges — no law covered it yet","Mitnick later ran a security firm; social engineering remains attack #1"]},
9:{facts:["AWS S3 outage: Feb 28, 2017, US-EAST-1, ~4 hours","Cause: one mistyped parameter in a playbook command","The AWS status dashboard's icons were hosted… on S3"]},
10:{facts:["Gate: 30 questions · 45 min · 70% · one retake after 7 days","Practical: user + app + IP + Event Viewer, narrated","Targeted review beats re-watching everything — patch only the misses"]},
11:{facts:["Pentium FDIV bug found by Prof. Thomas Nicely, Oct 1994","Intel's recall charge: $475M (≈$1B today)","Beep codes vary by BIOS vendor — keep the cheat card at the bench"],vis:"pc"},
12:{facts:["'Capacitor plague' peaked 1999–2007 across many board brands","SMART monitors reallocated sectors, spin retries, temperature","RAID mirrors disks in real time — including your mistakes. Not backup."],vis:"storage",vid:"1cyMTl_QXSc"},
13:{facts:["Laser process: charge→expose→develop→transfer→fuse→clean","Fuser runs ~180–200°C — smearing toner = it isn't heating","Repeating defect spacing identifies the exact roller (drum ≈ 75–94 mm)"],demo:"laser"},
14:{facts:["Facebook outage: Oct 4, 2021, ~6 hours — a BGP withdrawal","Internal tools & badge systems shared the dead network","169.254.x.x (APIPA) = 'I asked DHCP and nobody answered'"],vis:"ports"},
15:{facts:["Default credentials remain a top-3 home/SOHO compromise vector","WPS PIN attacks are why WPS goes OFF","Shadowing target: 3 supervised tickets before the Core 2 gate"]},
16:{facts:["Note 7: two recalls (Sept & Oct 2016), ~3M units, product killed","Li-ion swelling = gas from electrolyte breakdown — fire risk","Batteries are consumables: ~300–500 full cycles to ~80% health"]},
17:{facts:["Netflix DVD outage: Aug 2008, 3 days — the cloud decision followed","Migration completed 2016, eight years later","Chaos Monkey is open source — chaos engineering is now a discipline"]},
18:{facts:["The 500-mile email: a classic, well-documented sysadmin case (Trey Harris)","Light travels ~5.6 ms round-trip per 500 miles — the timeout was ~3 ms… in units","Minimal boot = CPU + 1 RAM stick + PSU: the fastest no-POST isolator"]},
19:{facts:["'MOST likely' = cheapest theory · 'FIRST' = simplest step","Eliminate 2 options and a guess becomes 50/50","Flag & return: never spend 5 minutes on a 1-mark question"]},
20:{facts:["Win98 BSOD demo: COMDEX, April 20, 1998 — plug-and-play scanner","NTFS: cumulative permissions, explicit Deny wins, stricter of share vs NTFS over network","UAC (2006, Vista) cut silent admin-level malware installs dramatically"]},
21:{facts:["sfc /scannow repairs protected system files from a local store","gpupdate /force pulls fresh domain policy immediately","PowerShell verbs are standardized: Get-, Set-, Restart-, Stop-"]},
22:{facts:["Linus' post: comp.os.minix, Aug 25, 1991","Android's kernel is Linux; macOS descends from BSD Unix","All of the TOP500 supercomputers run Linux (since 2017)"]},
23:{facts:["WannaCry: May 12, 2017 — ~230k machines, 150+ countries in a day","Kill-switch domain registered for $10.69 by Marcus Hutchins","MS17-010 patch had shipped March 14 — 2 months earlier"]},
24:{facts:["Target breach: Nov–Dec 2013, ~40M cards + 70M records","Entry: phished credentials of an HVAC vendor with network access","Cost: $200M+ in settlements; CEO and CIO both departed"]},
25:{facts:["CrowdStrike outage: July 19, 2024 — ~8.5M Windows devices","Fix: boot to safe mode, delete one .sys channel file, reboot","Airlines, hospitals, banks, broadcasters — largest IT outage ever"]},
26:{facts:["NotPetya damage estimate: $10B globally; Maersk alone ~$300M","49,000 laptops, 3,500+ servers rebuilt in ~10 days","The surviving Ghana DC was offline due to a local power cut"]},
27:{facts:["Steam bug (2015): rm -rf \"$STEAMROOT\"/* with an empty variable","Defense: quote variables, test for empty, echo before exec","PowerShell -WhatIf flag previews destructive commands"]},
28:{facts:["3 stations × 20 min · narration is the score","3 mentor-signed tickets due — logged, real experience","Passing ≈ A+-level technician in skills terms"]},
29:{facts:["Mirai/Dyn attack: Oct 21, 2016 — DNS provider flooded","Botnet: ~100k+ IoT devices on default credentials","Mirai's source code leaked — variants persist today"],vis:"osistack"},
30:{facts:["Wireshark is the world's standard analyzer — free, open source","3-way handshake: SYN → SYN/ACK → ACK","Capture only on lab networks or with written authorization"]},
31:{facts:["IANA exhausted the IPv4 free pool: Feb 3, 2011","Microsoft–Nortel deal: $7.5M for 666,624 addresses (~$11.25 each)","IPv6 = 340 undecillion addresses (3.4×10³⁸)"]},
32:{facts:["Design rule: size each subnet to DOUBLE its current need","Gateways at .1, servers low, DHCP scopes leave static room","An unwritten address plan is an outage with a delay timer"]},
33:{facts:["Beth Israel Deaconess network collapse: Nov 2002, ~4 days degraded","Cause analysis: spanning-tree loop / broadcast storm","802.1Q adds a 4-byte VLAN tag to each trunk frame"],vis:"vlan",demo:"storm"},
34:{facts:["Pakistan/YouTube hijack: Feb 24, 2008, ~2 hours global","BGP accepts the MOST SPECIFIC route — /24 beat /22","RPKI now cryptographically validates route origins (adoption growing)"],demo:"nat"},
35:{facts:["Parkes 'perytons' solved 2015: the staff microwave oven","2.4 GHz: only channels 1, 6, 11 don't overlap (in most regions)","Wi-Fi 7 (802.11be): multi-link operation across bands"],demo:"wifi"},
36:{facts:["DHCP lease: Discover → Offer → Request → Acknowledge (DORA)","Dyn attack proved DNS is a single point of failure at scale","Kerberos auth breaks beyond 5 minutes of clock drift — NTP matters"],demo:"dora"},
37:{facts:["Stuxnet: discovered June 2010; targeted Siemens S7 PLCs","It replayed normal sensor data while driving centrifuges to failure","Crossed the air gap via USB — 'offline' ≠ unreachable"]},
38:{facts:["AT&T collapse: Jan 15, 1990 — 9 hours, ~50M+ blocked calls","One switch's recovery message crashed its neighbors: cascade","Syslog severities: 0 emergency → 7 debug"]},
39:{facts:["Georgia/Armenia cable cut: March 28, 2011 — ~5 hours offline","Undersea cables: 100+ faults/year, mostly anchors & fishing","Bottom-up: cable → port/VLAN → IP/gateway → service → app"]},
40:{facts:["3 hidden faults · 45 minutes · narration mandatory","Map what WORKS first — it outlines the broken thing","One fix per re-test: fault interactions lie"]},
41:{facts:["Mock: 30 questions · 50 min · 70% · true exam conditions","Capstone declared today: build-out, defense, or improvement project","Review = miss list → targeted patch → short re-quiz"]},
42:{facts:["Rubric: accuracy · method · documentation · communication · independence","18/25 to pass · scored independently by two evaluators","Graduates leave exam-ready for the official CompTIA path"]}
};
SESSIONS.forEach(s=>{const e=EXTRA[s.n]||{};s.facts=e.facts||[];s.vis=e.vis||null;s.vid=e.vid||"";if(e.demo&&!s.demo)s.demo=e.demo;});
if(typeof module!=='undefined')module.exports=SESSIONS;

/* ===== MEDIA LAYER v3: more visuals (incl. evolution strips) + verified videos =====
   All YouTube IDs below were verified via search against PowerCert Animated Videos
   (and TechTerms for the OSI animation). Test each embed once before class.
   SPARE VERIFIED IDs (paste into any session's vid): DHCP e6-TaH5bkjo · Port forwarding 2G1ueMDgwxw ·
   Ethernet cables _NX99ad2FUA · ipconfig ZKhorleA5aA · netstat 8UZFpCQeXnM · ARP cn8Zxh9bPio ·
   HTTP hExRDVZHhig · Proxy 5cPIukqXe5w · Topologies zbqrNg4C98U · Bluetooth mPMGRILsOVk ·
   Default gateway pCcJFdYNamc · POP3vsIMAP SBaARws0hy4 */
const EXTRA2={
1:{vis:["cpuevo"]},
2:{vis:["pc","storageevo"]},
3:{vis:["osevo"]},
7:{vis:["homenet"],vid:"4_zSIXb7tLQ"},          /* PowerCert: LAN MAN WAN PAN */
11:{vis:["ramevo"],vid:"PVad0c2cljo"},           /* PowerCert: RAM Explained */
12:{vis:["storage"]},                            /* keeps SSD video from v2 */
14:{vis:["ports"],vid:"uwoD5YsGACg"},            /* PowerCert: TCP vs UDP */
16:{vis:["connevo"]},
17:{vis:["cloudstack"]},
23:{vis:["malwaretree"]},
24:{vis:["castle"]},
25:{vis:["bootladder"]},
29:{vis:["osistack"],vid:"vv4y_uOneC0"},         /* TechTerms: OSI Model animation */
30:{vis:["handshake"]},
31:{vid:"ThdO9beHhpA"},                          /* PowerCert: IPv4 vs IPv6 */
33:{vis:["vlan"]},
34:{vid:"FTUV0t6JaDA"},                          /* PowerCert: NAT */
35:{vis:["wifievo"],vid:"OxiY4yf6GGg"},          /* PowerCert: AP vs WiFi Router */
36:{vid:"mpQZVYPuDGU"},                          /* PowerCert: DNS */
39:{vid:"IIicPE38O-s"}                           /* PowerCert: Ping */
};
SESSIONS.forEach(s=>{
  const e=EXTRA2[s.n]||{};
  s.vis=e.vis||(s.vis?[s.vis]:[]);
  if(e.vid)s.vid=e.vid;
});
if(typeof module!=='undefined')module.exports=SESSIONS;
